import type { MetadataRoute } from 'next'

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://bitnook.example.com'

const routes = [
  '/',
  '/tools',
  '/tools/daily',
  '/tools/daily/timer',
  '/tools/daily/countdown',
  '/tools/daily/lottery',
  '/tools/daily/password',
  '/tools/daily/word-count',
  '/tools/daily/date-calc',
  '/tools/daily/stopwatch',
  '/tools/daily/world-clock',
  '/tools/finance',
  '/tools/finance/mortgage',
  '/tools/finance/exchange',
  '/tools/finance/retirement',
  '/tools/finance/compound',
  '/tools/finance/salary',
  '/tools/finance/deposit',
  '/tools/finance/loan-compare',
  '/tools/finance/roi',
  '/tools/health',
  '/tools/health/bmi',
  '/tools/health/heart-rate',
  '/tools/health/calories',
  '/tools/health/water-intake',
  '/tools/health/sleep',
  '/tools/health/steps',
  '/tools/health/heart-age',
  '/tools/health/blood-pressure',
  '/tools/convert',
  '/tools/convert/unit',
  '/tools/convert/radix',
  '/tools/convert/hash',
  '/tools/convert/qrcode',
  '/tools/convert/color',
  '/tools/convert/timestamp',
  '/tools/network',
  '/tools/network/ip-lookup',
  '/tools/network/dns',
  '/tools/network/speed-test',
  '/tools/network/ping',
  '/tools/network/port-scan',
  '/tools/network/wifi-info',
  '/tools/network/http-check',
  '/tools/network/ssl-check',
  '/tools/ai',
  '/tools/ai/gpu-calculator',
  '/games',
  '/games/tetris',
  '/games/minesweeper',
  '/games/snake',
  '/games/gomoku',
  '/games/match3',
  '/games/chess-international',
  '/games/chess-chinese',
  '/games/freecell',
  '/about',
  '/contact',
  '/privacy',
  '/terms',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: now,
    changeFrequency: route === '/' ? 'daily' : 'weekly',
    priority: route === '/' ? 1 : route.startsWith('/tools/finance') ? 0.85 : 0.7,
  }))
}
