import { CategorySlug } from './categories'

export type ToolStatus = 'active' | 'beta' | 'deprecated' | 'planned'
export type ToolType = 'calculator' | 'converter' | 'generator' | 'checker' | 'utility'
export type PrivacyMode = 'local' | 'network' | 'server'
export type ToolTier = 'S' | 'A' | 'B'

export interface ToolRegistryItem {
  slug: string
  category: CategorySlug
  name: string
  nameEn: string
  description: string
  descriptionEn: string
  icon: string
  color: string
  href: string
  status: ToolStatus
  toolType: ToolType
  privacyMode: PrivacyMode
  tier: ToolTier
  isPremium: boolean
  seoTitle: string
  seoTitleEn: string
  seoDescription: string
  seoDescriptionEn: string
  keywords: string[]
  keywordsEn: string[]
  relatedTools: string[]
  updatedAt: string
}

export const TOOLS: ToolRegistryItem[] = [
  // ==================== Daily Tools ====================
  {
    slug: 'timer',
    category: 'daily',
    name: '多功能计时器',
    nameEn: 'Multi-Task Timer',
    description: '支持多任务并行计时与番茄钟专注模式，精准到秒',
    descriptionEn: 'Multi-task parallel timer with Pomodoro focus mode and custom sound alarms',
    icon: 'Clock',
    color: '#3B82F6',
    href: '/tools/daily/timer',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '在线计时器与番茄钟 · 多任务专注倒数工具 - BitNook',
    seoTitleEn: 'Online Multi-Task Timer & Pomodoro Tracker - BitNook',
    seoDescription: '免费在线多任务计时器，支持并行计时、番茄工作法、标签管理与休息提醒，数据存储于本地浏览器。',
    seoDescriptionEn: 'Free online timer with parallel timers, Pomodoro technique intervals, and browser-local state storage.',
    keywords: ['在线计时器', '番茄钟', '倒数计时', '专注时钟', '任务计时'],
    keywordsEn: ['online timer', 'pomodoro timer', 'countdown', 'focus timer', 'task timer'],
    relatedTools: ['stopwatch', 'countdown', 'date-calc'],
    updatedAt: '2026-03-10',
  },
  {
    slug: 'countdown',
    category: 'daily',
    name: '目标日倒计时',
    nameEn: 'Target Countdown',
    description: '重要纪念日、考试、节日与事件目标实时倒计时',
    descriptionEn: 'Real-time countdown timer for birthdays, exams, holidays, and milestones',
    icon: 'Hourglass',
    color: '#3B82F6',
    href: '/tools/daily/countdown',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '在线倒计时器 · 纪念日与重要目标天数倒计 - BitNook',
    seoTitleEn: 'Online Target Date Countdown Calculator - BitNook',
    seoDescription: '精确计算距离目标日期的天、时、分、秒，支持常用节日一键选择，本地记录无需登录。',
    seoDescriptionEn: 'Calculate exact days, hours, and minutes remaining until your target events and exams.',
    keywords: ['在线倒计时', '高考倒计时', '纪念日倒数', '节日倒计时', '生日倒计时'],
    keywordsEn: ['countdown timer', 'event countdown', 'days until', 'holiday countdown'],
    relatedTools: ['timer', 'date-calc', 'world-clock'],
    updatedAt: '2026-03-10',
  },
  {
    slug: 'lottery',
    category: 'daily',
    name: '随机转盘抽奖',
    nameEn: 'Random Lucky Wheel',
    description: '自定义抽奖项目与权重的幸运转盘，支持防重复抽取与历史记录',
    descriptionEn: 'Customizable random spinner wheel with fair weighting, duplicate filtering, and history',
    icon: 'HelpCircle',
    color: '#3B82F6',
    href: '/tools/daily/lottery',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'B',
    isPremium: false,
    seoTitle: '在线随机抽奖转盘 · 公平摇号与随机决定器 - BitNook',
    seoTitleEn: 'Online Lucky Wheel & Random Decision Picker - BitNook',
    seoDescription: '适用于团队团建、课堂点名、吃什么选择与活动抽奖，完全在本地随机生成，公平透明。',
    seoDescriptionEn: 'Fair online decision spinner for raffles, classroom picks, and lunch decisions.',
    keywords: ['在线抽奖', '大转盘', '随机点名器', '随机决定', '今天吃什么'],
    keywordsEn: ['lucky wheel', 'random picker', 'name picker', 'decision maker'],
    relatedTools: ['password', 'word-count'],
    updatedAt: '2026-03-10',
  },
  {
    slug: 'password',
    category: 'daily',
    name: '安全密码生成器',
    nameEn: 'Secure Password Generator',
    description: '本地高强度随机密码生成，支持自定义字符集与易混淆字符排除',
    descriptionEn: 'High-entropy cryptographic random password generator created entirely in your browser',
    icon: 'Key',
    color: '#3B82F6',
    href: '/tools/daily/password',
    status: 'active',
    toolType: 'generator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '安全密码生成器 · 本地高强度随机密码批量生成 - BitNook',
    seoTitleEn: 'Secure Password Generator - Cryptographically Strong - BitNook',
    seoDescription: '使用浏览器原生 Web Crypto API 生成不可预测的强密码，绝不发送到任何远程服务器。',
    seoDescriptionEn: 'Generate strong, uncrackable passwords locally using cryptographic APIs. Zero network transmission.',
    keywords: ['密码生成器', '强密码', '随机密码', '安全密码', '防破解密码'],
    keywordsEn: ['password generator', 'secure password', 'random generator', 'entropy checker'],
    relatedTools: ['hash', 'qrcode'],
    updatedAt: '2026-03-15',
  },
  {
    slug: 'word-count',
    category: 'daily',
    name: '字数与文本分析',
    nameEn: 'Word Counter & Text Analyzer',
    description: '实时统计中文字数、英文单词、字符数、段落与预估阅读时长',
    descriptionEn: 'Instant text analysis for Chinese characters, English words, paragraphs, and reading time',
    icon: 'FileText',
    color: '#3B82F6',
    href: '/tools/daily/word-count',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '在线字数统计与文本分析工具 · 支持中英双语 - BitNook',
    seoTitleEn: 'Online Word Counter & Character Counter - BitNook',
    seoDescription: '精确统计中文字符、不含空格字数、英文单词、段落数、行数与朗读时长，写作与排版必备。',
    seoDescriptionEn: 'Count Chinese characters, words, letters, lines, and reading duration instantly in real time.',
    keywords: ['字数统计', '在线字数', '字符统计', '英文单词统计', '文本阅读时间'],
    keywordsEn: ['word counter', 'character count', 'word analysis', 'reading time calculator'],
    relatedTools: ['date-calc', 'password'],
    updatedAt: '2026-03-10',
  },
  {
    slug: 'date-calc',
    category: 'daily',
    name: '日期间隔与推算',
    nameEn: 'Date Interval Calculator',
    description: '计算两个日期间隔天数、工作日天数，以及按天数推算未来或过去日期',
    descriptionEn: 'Calculate days between two dates, workdays, and project future target dates',
    icon: 'Calendar',
    color: '#3B82F6',
    href: '/tools/daily/date-calc',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '日期间隔计算器 · 在线算天数与推算日期 - BitNook',
    seoTitleEn: 'Date Difference & Workdays Calculator - BitNook',
    seoDescription: '精确计算两个日期相差的天数、周数、月数，支持推算 N 天后具体是星期几与日期。',
    seoDescriptionEn: 'Calculate the exact duration between dates, working days, and date offsets.',
    keywords: ['日期间隔', '天数计算', '日期加减', '工作日计算', '日期相差'],
    keywordsEn: ['date calculator', 'days between dates', 'workdays', 'date add subtract'],
    relatedTools: ['countdown', 'timestamp', 'world-clock'],
    updatedAt: '2026-03-10',
  },
  {
    slug: 'stopwatch',
    category: 'daily',
    name: '高精度在线秒表',
    nameEn: 'High-Precision Stopwatch',
    description: '毫秒级精准秒表，支持分圈计次、最快/最慢圈标记与数据导出',
    descriptionEn: 'Millisecond stopwatch with lap splits, fastest/slowest lap detection, and data export',
    icon: 'Watch',
    color: '#3B82F6',
    href: '/tools/daily/stopwatch',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'B',
    isPremium: false,
    seoTitle: '在线高精度秒表 · 支持毫秒与分圈记录 - BitNook',
    seoTitleEn: 'Online Stopwatch with Lap Records & Milliseconds - BitNook',
    seoDescription: '高精度在线计时秒表，支持键盘快捷键空格暂停/继续，多圈记录分析，适合运动与工作计时。',
    seoDescriptionEn: 'Precision millisecond stopwatch with lap split records and keyboard hotkeys.',
    keywords: ['在线秒表', '毫秒秒表', '计次秒表', '运动计时器'],
    keywordsEn: ['online stopwatch', 'lap timer', 'precision timer'],
    relatedTools: ['timer', 'countdown'],
    updatedAt: '2026-03-10',
  },
  {
    slug: 'world-clock',
    category: 'daily',
    name: '世界时钟与时区转换',
    nameEn: 'World Clock & Timezone Converter',
    description: '全球主要城市实时时间对照，时差换算与跨国会议时间规划',
    descriptionEn: 'Real-time global city clocks, UTC timezone offsets, and international meeting planner',
    icon: 'Globe',
    color: '#3B82F6',
    href: '/tools/daily/world-clock',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'B',
    isPremium: false,
    seoTitle: '世界时钟 · 全球城市时差与时区对照表 - BitNook',
    seoTitleEn: 'World Clock & Global Time Zone Converter - BitNook',
    seoDescription: '北京、伦敦、纽约、东京等全球各时区城市时间实时查看，支持夏令时换算与跨时区会议对齐。',
    seoDescriptionEn: 'Check current local times in major cities worldwide with timezone comparison.',
    keywords: ['世界时钟', '时区换算', '时差查询', '国际会议时间', 'UTC换算'],
    keywordsEn: ['world clock', 'time zone converter', 'utc offset', 'meeting planner'],
    relatedTools: ['timestamp', 'date-calc'],
    updatedAt: '2026-03-10',
  },

  // ==================== Finance Tools ====================
  {
    slug: 'mortgage',
    category: 'finance',
    name: '房贷计算器',
    nameEn: 'Mortgage Calculator',
    description: '支持按房屋总价或贷款金额独立计算，等额本息与等额本金对比分析',
    descriptionEn: 'Comprehensive mortgage calculator for equal payments and equal principal with full amortization schedules',
    icon: 'Home',
    color: '#10B981',
    href: '/tools/finance/mortgage',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '房贷计算器2026最新版 · 等额本息与等额本金还款明细对比 - BitNook',
    seoTitleEn: 'Mortgage Calculator with Amortization Schedule - BitNook',
    seoDescription: '支持商业贷款、公积金贷款及组合贷款测算，首月还款、总利息支出对比与逐月还款计划表。',
    seoDescriptionEn: 'Calculate monthly payments, total interest, and amortization schedule for equal payment vs equal principal mortgages.',
    keywords: ['房贷计算器', '最新房贷利率', '等额本息', '等额本金', '提前还贷计算', '房贷月供'],
    keywordsEn: ['mortgage calculator', 'amortization schedule', 'home loan payment', 'loan interest'],
    relatedTools: ['loan-compare', 'compound', 'salary', 'deposit'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'exchange',
    category: 'finance',
    name: '参考汇率换算',
    nameEn: 'Reference Currency Converter',
    description: '主流货币基准参考汇率双向换算，附带数据来源与更新时间说明',
    descriptionEn: 'Multi-currency converter based on published central bank benchmark reference rates',
    icon: 'DollarSign',
    color: '#10B981',
    href: '/tools/finance/exchange',
    status: 'active',
    toolType: 'converter',
    privacyMode: 'network',
    tier: 'S',
    isPremium: false,
    seoTitle: '外汇汇率换算器 · 人民币/美元/欧元基准参考汇率 - BitNook',
    seoTitleEn: 'Currency Converter - Benchmark Reference Rates - BitNook',
    seoDescription: '提供美元、欧元、英镑、日元等常用货币对人民币的基准参考汇率换算，清晰标注计算依据与免责声明。',
    seoDescriptionEn: 'Convert between CNY, USD, EUR, GBP, JPY, and other global currencies using benchmark reference values.',
    keywords: ['汇率换算', '人民币汇率', '美元汇率', '货币兑换', '今日外汇牌价参考'],
    keywordsEn: ['currency converter', 'exchange rate', 'cny to usd', 'forex calculator'],
    relatedTools: ['mortgage', 'deposit', 'compound'],
    updatedAt: '2026-03-20',
  },
  {
    slug: 'retirement',
    category: 'finance',
    name: '渐进式延迟退休计算器',
    nameEn: 'China Statutory Retirement Age Calculator',
    description: '基于2025年起国家法定渐进式延迟退休年龄改革规则，支持男女、干部与工人精算',
    descriptionEn: 'Statutory retirement age calculator implementing China 2025 progressive reform policies',
    icon: 'UserCheck',
    color: '#10B981',
    href: '/tools/finance/retirement',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '延迟退休计算器2026最新政策 · 法定退休年龄与弹性退休测算 - BitNook',
    seoTitleEn: 'Retirement Age Calculator - Progressive Policy Rules - BitNook',
    seoDescription: '严格依据全国人大《关于实施渐进式延迟法定退休年龄的决定》，按出生年月、原退休类别精确测算延迟月份、法定退休时间及弹性早退/晚退范围。',
    seoDescriptionEn: 'Accurate progressive retirement age calculator based on the official 2025 China statutory pension reforms.',
    keywords: ['延迟退休计算器', '法定退休年龄', '渐进式延迟退休', '弹性提前退休', '弹性延迟退休', '退休时间测算'],
    keywordsEn: ['retirement calculator', 'pension age', 'statutory retirement', 'early retirement'],
    relatedTools: ['salary', 'compound', 'mortgage'],
    updatedAt: '2026-03-20',
  },
  {
    slug: 'compound',
    category: 'finance',
    name: '复利投资增长计算器',
    nameEn: 'Compound Interest Calculator',
    description: '定期定投、初始本金复利增长测算，本金与收益复利效应可视化',
    descriptionEn: 'Simulate long-term investment growth with initial deposit, regular contributions, and compounding',
    icon: 'TrendingUp',
    color: '#10B981',
    href: '/tools/finance/compound',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '复利计算器在线计算 · 基金定投与长期理财收益测算 - BitNook',
    seoTitleEn: 'Compound Interest & Investment Growth Calculator - BitNook',
    seoDescription: '输入初始本金、年化收益率、投资年限与每月定投金额，计算本金累积与利息收益复利曲线。',
    seoDescriptionEn: 'Calculate future wealth with compounding returns, periodic deposits, and annual growth tables.',
    keywords: ['复利计算器', '投资理财', '基金定投计算', '利滚利', '年化收益率'],
    keywordsEn: ['compound interest', 'investment calculator', 'compound growth', 'savings calculator'],
    relatedTools: ['deposit', 'roi', 'mortgage', 'salary'],
    updatedAt: '2026-03-15',
  },
  {
    slug: 'salary',
    category: 'finance',
    name: '工资个税与税后收入估算',
    nameEn: 'Salary & Individual Income Tax Estimator',
    description: '中国居民综合所得个税七级累进预扣估算，支持五险一金与专项附加扣除配置',
    descriptionEn: 'Chinese resident individual income tax estimator with social insurance, housing fund, and special deductions',
    icon: 'Wallet',
    color: '#10B981',
    href: '/tools/finance/salary',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '工资计算器2026 · 税前税后工资与个人所得税估算 - BitNook',
    seoTitleEn: 'Salary & Net Pay Calculator - Income Tax Estimator - BitNook',
    seoDescription: '根据现行个人所得税法与七级超额累进税率，结合起征点5000元、五险一金费率与专项附加扣除，测算税后到手收入。',
    seoDescriptionEn: 'Estimate net monthly take-home salary after individual income tax, social security, and housing fund deductions.',
    keywords: ['工资计算器', '税后工资计算', '个税计算器', '五险一金计算', '专项附加扣除'],
    keywordsEn: ['salary calculator', 'take home pay', 'income tax calculator', 'payroll deduction'],
    relatedTools: ['retirement', 'mortgage', 'compound'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'deposit',
    category: 'finance',
    name: '存款收益计算器',
    nameEn: 'Deposit Interest Calculator',
    description: '活期、定期与大额存单基准利率收益测算，明示数据来源与参考标准',
    descriptionEn: 'Calculate deposit interest for demand, term, and certificates of deposit using benchmark datasets',
    icon: 'PiggyBank',
    color: '#10B981',
    href: '/tools/finance/deposit',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '银行存款利率计算器 · 活期定期存款利息对比 - BitNook',
    seoTitleEn: 'Bank Deposit Yield Calculator - BitNook',
    seoDescription: '提供各期限定期存款与大额存单收益估算，对比不同期限利息差异，清晰展示参考利率基准。',
    seoDescriptionEn: 'Compare interest earnings across different deposit terms and benchmark banking rates.',
    keywords: ['存款计算器', '定期存款利率', '银行利息计算', '大额存单收益', '活期利息'],
    keywordsEn: ['deposit calculator', 'bank interest', 'fixed deposit', 'certificate of deposit'],
    relatedTools: ['compound', 'mortgage', 'roi'],
    updatedAt: '2026-03-20',
  },
  {
    slug: 'loan-compare',
    category: 'finance',
    name: '贷款方案多维度比价',
    nameEn: 'Loan Plan Comparison',
    description: '对比不同贷款机构金额、期限、还款方式与实际年化利率差异',
    descriptionEn: 'Compare multiple loan options side-by-side by monthly cost, total interest, and effective APR',
    icon: 'Scale',
    color: '#10B981',
    href: '/tools/finance/loan-compare',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '贷款比价计算器 · 多方案综合成本与利息对比 - BitNook',
    seoTitleEn: 'Loan Comparison Calculator - Side-by-Side Analysis - BitNook',
    seoDescription: '同时输入多个贷款方案，自动对比每月月供、总利息支出与实际资金成本，助您做出理性借贷选择。',
    seoDescriptionEn: 'Compare different loan offers side by side to find the lowest total cost and monthly payment.',
    keywords: ['贷款比价', '车贷计算', '消费贷对比', '实际年化利率', '借款方案对比'],
    keywordsEn: ['loan comparison', 'apr comparison', 'loan cost', 'borrowing comparison'],
    relatedTools: ['mortgage', 'roi', 'compound'],
    updatedAt: '2026-03-15',
  },
  {
    slug: 'roi',
    category: 'finance',
    name: '投资回报与IRR/NPV计算',
    nameEn: 'ROI, IRR & NPV Calculator',
    description: '真实计算简单投资回报率(ROI)、现金流净现值(NPV)及内部收益率(IRR)',
    descriptionEn: 'Accurate financial calculation for Return on Investment (ROI), Net Present Value (NPV), and Internal Rate of Return (IRR)',
    icon: 'BarChart2',
    color: '#10B981',
    href: '/tools/finance/roi',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: 'ROI/IRR/NPV投资回报率计算器 · 真实现金流测算 - BitNook',
    seoTitleEn: 'ROI, IRR & NPV Calculator - Real Cash Flow Discounting - BitNook',
    seoDescription: '支持逐年预期现金流输入，使用牛顿法求解真实内部收益率 (IRR)，精确计算折现净现值 (NPV) 与回报率。',
    seoDescriptionEn: 'Evaluate capital investments with exact ROI, NPV discounted cash flows, and Newton-Raphson IRR solver.',
    keywords: ['ROI计算器', 'IRR内部收益率', 'NPV净现值', '投资回报率', '财务投资评估'],
    keywordsEn: ['roi calculator', 'irr calculator', 'npv calculator', 'internal rate of return', 'net present value'],
    relatedTools: ['compound', 'loan-compare', 'deposit'],
    updatedAt: '2026-03-25',
  },

  // ==================== Health Tools ====================
  {
    slug: 'bmi',
    category: 'health',
    name: 'BMI 体质指数评估',
    nameEn: 'BMI Calculator',
    description: '根据世界卫生组织 (WHO) 与中国成人体质分类标准评估体重健康范围',
    descriptionEn: 'Body Mass Index calculator evaluated against WHO and Chinese adult health classification standards',
    icon: 'Activity',
    color: '#EF4444',
    href: '/tools/health/bmi',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: 'BMI计算器在线评估 · 中国成人体质指数标准 - BitNook',
    seoTitleEn: 'BMI Calculator - Body Mass Index Evaluation - BitNook',
    seoDescription: '输入身高体重，快速测算 BMI 指数、理想体重区间与健康分类建议，注明适用范围与医学免责声明。',
    seoDescriptionEn: 'Calculate your Body Mass Index (BMI) and healthy weight range with clear scientific criteria.',
    keywords: ['BMI计算器', '体质指数', '标准体重计算', '身材健康评估', '肥胖自测'],
    keywordsEn: ['bmi calculator', 'body mass index', 'healthy weight', 'bmi chart'],
    relatedTools: ['calories', 'heart-rate', 'steps'],
    updatedAt: '2026-03-15',
  },
  {
    slug: 'calories',
    category: 'health',
    name: '卡路里与每日能量消耗 (TDEE)',
    nameEn: 'Calorie & TDEE Calculator',
    description: '基于 Mifflin-St Jeor 权威公式测算基础代谢率 (BMR) 与活动消耗',
    descriptionEn: 'Daily calorie and energy expenditure estimation using the verified Mifflin-St Jeor equation',
    icon: 'Flame',
    color: '#EF4444',
    href: '/tools/health/calories',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: 'TDEE每日热量消耗与基础代谢计算器 · 减脂增肌热量预算 - BitNook',
    seoTitleEn: 'TDEE & Basal Metabolic Rate (BMR) Calculator - BitNook',
    seoDescription: '根据年龄、性别、身高体重与日常运动频率，计算每日总能量消耗 (TDEE) 及减脂、增肌、维持目标热量摄入建议。',
    seoDescriptionEn: 'Calculate Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE) for fitness planning.',
    keywords: ['TDEE计算器', '基础代谢率', '卡路里计算', '减脂热量缺口', '每日热量消耗'],
    keywordsEn: ['tdee calculator', 'bmr calculator', 'calorie intake', 'energy expenditure'],
    relatedTools: ['bmi', 'heart-rate', 'water-intake'],
    updatedAt: '2026-03-15',
  },
  {
    slug: 'heart-rate',
    category: 'health',
    name: '运动心率区间规划',
    nameEn: 'Heart Rate Training Zones',
    description: '基于田中公式与卡沃宁储备心率法，规划燃脂、有氧与极限运动心率靶区',
    descriptionEn: 'Target workout heart rate zones calculated using Tanaka and Karvonen reserve methods',
    icon: 'Heart',
    color: '#EF4444',
    href: '/tools/health/heart-rate',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '目标运动心率区间计算器 · 燃脂与有氧耐力心率靶区 - BitNook',
    seoTitleEn: 'Target Heart Rate Zones & Karvonen Calculator - BitNook',
    seoDescription: '根据年龄与静息心率，精确划定热身、燃脂、有氧耐力、无氧耐力五级运动心率区间，提升科学训练效率。',
    seoDescriptionEn: 'Determine your aerobic, fat burn, and anaerobic training heart rate zones for safe exercise.',
    keywords: ['运动心率计算', '燃脂心率', '最大心率', '储备心率法', '跑步心率区间'],
    keywordsEn: ['target heart rate', 'karvonen formula', 'training zones', 'fat burn zone'],
    relatedTools: ['calories', 'bmi', 'steps'],
    updatedAt: '2026-03-15',
  },
  {
    slug: 'blood-pressure',
    category: 'health',
    name: '血压记录与分级参考',
    nameEn: 'Blood Pressure Log & Classification',
    description: '参照《中国高血压防治指南》提供血压分级对照与本地趋势记录，非医疗诊断',
    descriptionEn: 'Blood pressure reference classifier and local diary based on standard hypertension guidelines',
    icon: 'HeartPulse',
    color: '#EF4444',
    href: '/tools/health/blood-pressure',
    status: 'active',
    toolType: 'checker',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '血压标准对照表与日常记录 · 血压分级参考工具 - BitNook',
    seoTitleEn: 'Blood Pressure Tracker & Classification Guide - BitNook',
    seoDescription: '输入收缩压与舒张压，对照正常血压、正常高值及1/2/3级高血压标准，支持本地记录保存与健康宣教参考。',
    seoDescriptionEn: 'Track systolic and diastolic blood pressure readings and view standard clinical classification zones.',
    keywords: ['血压标准对照表', '血压正常范围', '高血压分级', '低血压标准', '血压日常记录'],
    keywordsEn: ['blood pressure chart', 'hypertension levels', 'blood pressure tracker'],
    relatedTools: ['heart-rate', 'bmi', 'water-intake'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'sleep',
    category: 'health',
    name: '睡眠周期与作息规划器',
    nameEn: 'Sleep Cycle & Bedtime Planner',
    description: '基于人体约90分钟睡眠周期规律，规划最佳入睡与晨醒时间，改善晨起疲劳',
    descriptionEn: 'Calculate optimal bedtimes and wake-up alarms based on natural sleep cycles and sleep latency',
    icon: 'Moon',
    color: '#EF4444',
    href: '/tools/health/sleep',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '睡眠周期计算器 · 科学作息入睡与起床时间规划 - BitNook',
    seoTitleEn: 'Sleep Cycle & Bedtime Calculator - BitNook',
    seoDescription: '根据大约 90 分钟的 REM/非REM 睡眠周期与15分钟平均入睡耗时，推算醒来不困倦的黄金时间点。',
    seoDescriptionEn: 'Find the best times to fall asleep or wake up feeling refreshed according to natural sleep cycles.',
    keywords: ['睡眠计算器', '最佳起床时间', '睡眠周期', '几点睡觉', '快速入睡规划'],
    keywordsEn: ['sleep cycle calculator', 'bedtime planner', 'wake up refreshed', 'sleep stages'],
    relatedTools: ['timer', 'water-intake', 'calories'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'steps',
    category: 'health',
    name: '步行距离与活动估算',
    nameEn: 'Walking Distance & Steps Estimator',
    description: '按身高步幅算法换算步数、公里距离、活动时长与粗估运动消耗',
    descriptionEn: 'Convert step counts into walking distance, active minutes, and estimated energy expenditure',
    icon: 'Footprints',
    color: '#EF4444',
    href: '/tools/health/steps',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'B',
    isPremium: false,
    seoTitle: '步数换算公里距离与活动估算器 · 科学健步参考 - BitNook',
    seoTitleEn: 'Steps to Distance & Active Walking Calculator - BitNook',
    seoDescription: '根据身高计算个性化步幅，将每日步数转换为真实公里里程与步行时间，作为日常活动规划参考。',
    seoDescriptionEn: 'Estimate walking distance in kilometers and miles from daily step counts with custom stride length.',
    keywords: ['步数换算公里', '步幅计算', '一天走一万步是多少公里', '步行运动规划'],
    keywordsEn: ['steps to distance', 'stride length calculator', 'step tracker converter'],
    relatedTools: ['calories', 'bmi', 'heart-rate'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'water-intake',
    category: 'health',
    name: '每日饮水估算与计划',
    nameEn: 'Daily Water Intake Planner',
    description: '结合体重基线、日常活动强度与气候因素，规划每日水分摄入与提醒时间表',
    descriptionEn: 'Daily hydration estimation and intake schedule based on body weight and activity levels',
    icon: 'Droplets',
    color: '#EF4444',
    href: '/tools/health/water-intake',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'B',
    isPremium: false,
    seoTitle: '每日饮水量计算器 · 科学补水规划与健康提醒 - BitNook',
    seoTitleEn: 'Daily Water Intake Calculator & Hydration Planner - BitNook',
    seoDescription: '按每公斤体重30-35ml推荐基线及运动出汗量，估算每日适宜饮水量，生成分段饮水打卡时间建议。',
    seoDescriptionEn: 'Calculate recommended daily water intake based on body weight, climate, and exercise frequency.',
    keywords: ['每日饮水量计算', '一天喝多少水合适', '饮水时间表', '科学补水规划'],
    keywordsEn: ['water intake calculator', 'hydration planner', 'daily water needs'],
    relatedTools: ['calories', 'sleep', 'bmi'],
    updatedAt: '2026-03-25',
  },

  // ==================== Format Conversion ====================
  {
    slug: 'color',
    category: 'convert',
    name: '多模式颜色转换器',
    nameEn: 'Color Code Converter',
    description: 'HEX、RGB、RGBA、HSL、HSLA、HSV 与 CMYK 颜色代码双向互转与取色对比',
    descriptionEn: 'Bidirectional color code conversions across HEX, RGB, RGBA, HSL, HSLA, HSV, and CMYK with live preview',
    icon: 'Palette',
    color: '#F59E0B',
    href: '/tools/convert/color',
    status: 'active',
    toolType: 'converter',
    privacyMode: 'local',
    tier: 'A',
    isPremium: false,
    seoTitle: '在线颜色转换器 · HEX/RGB/HSL/CMYK色彩模式互转 - BitNook',
    seoTitleEn: 'Color Converter - HEX, RGB, HSL, CMYK Code Tool - BitNook',
    seoDescription: '支持十六进制 HEX、RGB、HSL、HSV、印刷 CMYK 等主流色彩空间即时换算，色值复制与合法性校验。',
    seoDescriptionEn: 'Convert HEX color codes to RGB, HSL, and CMYK with live preview and one-click copy.',
    keywords: ['颜色转换器', 'HEX转RGB', 'RGB转HSL', 'CMYK转换', '色值换算', '调色板'],
    keywordsEn: ['color converter', 'hex to rgb', 'rgb to hsl', 'color code picker'],
    relatedTools: ['qrcode', 'unit', 'hash'],
    updatedAt: '2026-03-20',
  },
  {
    slug: 'unit',
    category: 'convert',
    name: '多功能单位换算器',
    nameEn: 'Comprehensive Unit Converter',
    description: '涵盖长度、重量、面积、体积、温度、时间、速度、数据容量、压力与能量',
    descriptionEn: 'Universal unit converter covering length, weight, area, volume, temperature, time, speed, storage, pressure, and energy',
    icon: 'Layers',
    color: '#F59E0B',
    href: '/tools/convert/unit',
    status: 'active',
    toolType: 'converter',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '通用单位换算器 · 长度/重量/温度/面积/数据容量换算 - BitNook',
    seoTitleEn: 'Universal Unit Converter - Length, Weight, Area & More - BitNook',
    seoDescription: '全面支持公制、英制与国际单位制即时换算，支持高精度科学计算与常用换算关系表。',
    seoDescriptionEn: 'Convert between metric and imperial units across 10 essential measurement categories.',
    keywords: ['单位换算', '长度换算', '重量转换', '温度华氏摄氏度换算', '数据容量转换', '面积单位换算'],
    keywordsEn: ['unit converter', 'metric converter', 'length conversion', 'weight converter'],
    relatedTools: ['radix', 'timestamp', 'color'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'radix',
    category: 'convert',
    name: '高精度进制转换 (BigInt)',
    nameEn: 'Radix Base Converter (BigInt)',
    description: '二进制、八进制、十进制与十六进制严格校验互转，支持超大整数无溢出',
    descriptionEn: 'Arbitrary-precision integer base converter supporting binary, octal, decimal, and hexadecimal with BigInt',
    icon: 'Binary',
    color: '#F59E0B',
    href: '/tools/convert/radix',
    status: 'active',
    toolType: 'converter',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '进制转换器 · 2/8/10/16进制高精度转换工具 - BitNook',
    seoTitleEn: 'Binary, Octal, Decimal, Hex Base Converter (BigInt) - BitNook',
    seoDescription: '使用 JavaScript 原生 BigInt 实现任意大整数进制互转，输入字符严格格式校验，杜绝截断与精度损失。',
    seoDescriptionEn: 'Convert arbitrarily large integers between binary, octal, decimal, and hex without precision loss.',
    keywords: ['进制转换器', '二进制转十六进制', '十进制转二进制', '大数进制转换', 'BigInt进制换算'],
    keywordsEn: ['radix converter', 'base converter', 'binary to hex', 'hex to decimal'],
    relatedTools: ['hash', 'timestamp', 'unit'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'hash',
    category: 'convert',
    name: '哈希散列计算器',
    nameEn: 'Hash Generator (Text & File)',
    description: '浏览器原生 Web Crypto 本地快速计算文本与文件的 SHA-256、SHA-512、SHA-384、SHA-1',
    descriptionEn: 'Compute SHA-256, SHA-512, SHA-384, and legacy SHA-1 for text and local files securely in your browser',
    icon: 'Hash',
    color: '#F59E0B',
    href: '/tools/convert/hash',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '在线哈希计算器 · 本地文本与文件SHA256/SHA512校验 - BitNook',
    seoTitleEn: 'Online Hash Generator - SHA-256, SHA-512 Text & File Hashes - BitNook',
    seoDescription: '文本及本地文件哈希计算，使用浏览器原生安全算法接口，文件数据不经过网络上传，安全保护隐私。',
    seoDescriptionEn: 'Generate cryptographic hashes for text strings and local files without uploading data to servers.',
    keywords: ['哈希计算器', 'SHA256在线计算', '文件哈希校验', 'SHA512生成器', '文本Hash计算'],
    keywordsEn: ['hash generator', 'sha256 calculator', 'file checksum', 'sha512 hash'],
    relatedTools: ['password', 'qrcode', 'radix'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'qrcode',
    category: 'convert',
    name: '本地二维码生成器',
    nameEn: 'Offline QR Code Generator',
    description: '纯浏览器本地实时生成文本、网址、WiFi 连接、电子名片与邮件二维码，无隐私泄露',
    descriptionEn: 'Generate QR codes for text, URLs, WiFi networks, and vCards purely client-side without third-party servers',
    icon: 'QrCode',
    color: '#F59E0B',
    href: '/tools/convert/qrcode',
    status: 'active',
    toolType: 'generator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '在线二维码生成器 · 本地离线安全生成与高清下载 - BitNook',
    seoTitleEn: 'Offline QR Code Generator - Safe Local Generation - BitNook',
    seoDescription: '绝不将用户输入发送给第三方服务器，纯前端即时渲染二维码，支持高清 PNG 下载与尺寸调节。',
    seoDescriptionEn: 'Create QR codes locally in your browser. Zero tracking, zero third-party calls, fast PNG download.',
    keywords: ['二维码生成器', '在线二维码', '网址二维码', 'WiFi二维码', '二维码高清下载'],
    keywordsEn: ['qr code generator', 'offline qr code', 'wifi qr code', 'vcard qr code'],
    relatedTools: ['color', 'password', 'hash'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'timestamp',
    category: 'convert',
    name: 'Unix 时间戳互转',
    nameEn: 'Unix Timestamp Converter',
    description: '秒级与毫秒级时间戳、国际 ISO 格式及本地日期时间精确双向转换',
    descriptionEn: 'Bidirectional converter between Unix timestamps (seconds & milliseconds) and human-readable dates',
    icon: 'Clock3',
    color: '#F59E0B',
    href: '/tools/convert/timestamp',
    status: 'active',
    toolType: 'converter',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: 'Unix时间戳转换工具 · 秒与毫秒时间戳与日期互转 - BitNook',
    seoTitleEn: 'Unix Timestamp Converter - Seconds & Milliseconds - BitNook',
    seoDescription: '开发者常用时间戳转换，支持实时当前时间戳、指定时间戳转换为北京时间/UTC时间，及日期生成时间戳。',
    seoDescriptionEn: 'Convert Unix epoch timestamps to human-readable dates and vice versa with local timezone support.',
    keywords: ['时间戳转换', 'Unix时间戳', '毫秒时间戳', '时间戳转日期', '在线时间戳工具'],
    keywordsEn: ['timestamp converter', 'unix timestamp', 'epoch converter', 'date to timestamp'],
    relatedTools: ['date-calc', 'world-clock', 'radix'],
    updatedAt: '2026-03-20',
  },

  // ==================== Network Tools ====================
  {
    slug: 'dns',
    category: 'network',
    name: 'DNS 记录解析查询',
    nameEn: 'DNS Lookup (DoH)',
    description: '通过官方 DNS over HTTPS (DoH) 真实查询 A、AAAA、CNAME、MX、TXT、NS 记录',
    descriptionEn: 'Query public DNS records over encrypted DNS-over-HTTPS (Cloudflare & Google DoH) with TTL and timestamps',
    icon: 'Database',
    color: '#8B5CF6',
    href: '/tools/network/dns',
    status: 'active',
    toolType: 'checker',
    privacyMode: 'network',
    tier: 'A',
    isPremium: false,
    seoTitle: '在线DNS查询工具 · 域名解析A/AAAA/CNAME/MX记录查询 - BitNook',
    seoTitleEn: 'Online DNS Lookup Tool (DNS-over-HTTPS) - BitNook',
    seoDescription: '通过安全加密 DoH 节点真实查询全球域名 DNS 解析记录，显示 TTL 缓存时长、真实解析结果与查询时间戳。',
    seoDescriptionEn: 'Inspect authoritative and cached DNS records for domains using verified DNS-over-HTTPS providers.',
    keywords: ['DNS查询', '域名解析查询', 'A记录查询', 'MX记录', 'DoH查询', 'DNS检测'],
    keywordsEn: ['dns lookup', 'dns records', 'a record check', 'mx record', 'doh resolver'],
    relatedTools: ['ip-lookup', 'http-check', 'ping'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'ip-lookup',
    category: 'network',
    name: 'IP 归属与地理位置查询',
    nameEn: 'IP Geolocation Lookup',
    description: '查询 IP 地址国家、省市城市、自治系统 ASN、所属运营商与时区详情',
    descriptionEn: 'Lookup IP geolocation, autonomous system number (ASN), organization, city, and timezone',
    icon: 'MapPin',
    color: '#8B5CF6',
    href: '/tools/network/ip-lookup',
    status: 'active',
    toolType: 'checker',
    privacyMode: 'network',
    tier: 'A',
    isPremium: false,
    seoTitle: 'IP地址查询与归属地检测 · 运营商与ASN信息 - BitNook',
    seoTitleEn: 'IP Geolocation & ASN Lookup Tool - BitNook',
    seoDescription: '一键检测本机公网 IP 地址，或输入任意指定 IPv4/IPv6 查询地理位置、ISP 网络服务商与 ASN 路由编号。',
    seoDescriptionEn: 'Discover IP geolocation, country, city, ASN number, and ISP information accurately.',
    keywords: ['IP查询', '我的IP地址', 'IP归属地', 'IP地理位置', 'ASN查询', '公网IP'],
    keywordsEn: ['ip lookup', 'my ip address', 'ip geolocation', 'whois ip', 'asn lookup'],
    relatedTools: ['dns', 'wifi-info', 'http-check'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'http-check',
    category: 'network',
    name: 'HTTP 状态与连通性检测',
    nameEn: 'HTTP Status & Connectivity Checker',
    description: '带严格 SSRF 安全防护的真实目标站点 HTTP 响应状态码、耗时与基础标头检测',
    descriptionEn: 'Check real website HTTP response status, redirect paths, latency, and headers with SSRF protection',
    icon: 'Globe',
    color: '#8B5CF6',
    href: '/tools/network/http-check',
    status: 'active',
    toolType: 'checker',
    privacyMode: 'server',
    tier: 'A',
    isPremium: false,
    seoTitle: 'HTTP状态码检测工具 · 真实网站状态与响应耗时测试 - BitNook',
    seoTitleEn: 'HTTP Status Code & Website Header Checker - BitNook',
    seoDescription: '真实检测网站 200、301、302、404、500 等状态码与响应时间，安全阻止内网穿透与伪造数据。',
    seoDescriptionEn: 'Safely inspect live HTTP status codes, response times, and server response headers.',
    keywords: ['HTTP检测', '网站状态码', '301重定向检测', '网页连通性测试', 'HTTP状态查询'],
    keywordsEn: ['http status checker', 'status code test', 'website connectivity', 'response headers'],
    relatedTools: ['ping', 'dns', 'ip-lookup'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'ping',
    category: 'network',
    name: 'HTTP 延迟连通性测试',
    nameEn: 'HTTP Latency Test',
    description: '真实测试客户端对目标网络端点的 HTTP/HTTPS 往返往来延迟与可用性',
    descriptionEn: 'Measure round-trip web request latency and reachability to target web endpoints accurately',
    icon: 'Activity',
    color: '#8B5CF6',
    href: '/tools/network/ping',
    status: 'active',
    toolType: 'checker',
    privacyMode: 'network',
    tier: 'A',
    isPremium: false,
    seoTitle: 'HTTP延迟测试工具 · 网站网络连接与响应速度测算 - BitNook',
    seoTitleEn: 'HTTP Latency & Web Response Speed Test - BitNook',
    seoDescription: '通过浏览器对指定站点发出可控轻量网络往返请求，测量实际网络往返 RTT 时延与波动情况。',
    seoDescriptionEn: 'Real round-trip latency measurements to test website responsiveness from your browser.',
    keywords: ['延迟测试', 'Ping测试', '网络延迟', '网站测速', 'HTTP延迟'],
    keywordsEn: ['latency test', 'ping tool', 'http ping', 'network latency test'],
    relatedTools: ['http-check', 'dns', 'wifi-info'],
    updatedAt: '2026-03-25',
  },
  {
    slug: 'wifi-info',
    category: 'network',
    name: '浏览器网络连接状态',
    nameEn: 'Browser Network Info',
    description: '通过浏览器原生 Network Information API 读取当前网络连接类型、下行带宽与 RTT 估算',
    descriptionEn: 'Inspect browser connection type, estimated downlink bandwidth, and RTT via Network Information APIs',
    icon: 'Wifi',
    color: '#8B5CF6',
    href: '/tools/network/wifi-info',
    status: 'active',
    toolType: 'utility',
    privacyMode: 'local',
    tier: 'B',
    isPremium: false,
    seoTitle: '浏览器网络连接状态信息 · 网络类型与下行带宽检测 - BitNook',
    seoTitleEn: 'Browser Network Information & Bandwidth Stats - BitNook',
    seoDescription: '真实检测当前浏览器获取的 effectiveType、downlink、rtt 与省流模式参数，明确告知浏览器兼容性边界。',
    seoDescriptionEn: 'View real connection speed, round-trip time, and online state reported by your browser.',
    keywords: ['网络连接信息', '浏览器网络状态', '网络带宽测试', '有效网络类型', 'Network API'],
    keywordsEn: ['browser network info', 'connection type', 'downlink speed', 'effective type'],
    relatedTools: ['ping', 'ip-lookup', 'http-check'],
    updatedAt: '2026-03-25',
  },

  // ==================== AI Tools ====================
  {
    slug: 'gpu-calculator',
    category: 'ai',
    name: '大模型显存估算器',
    nameEn: 'LLM VRAM & GPU Calculator',
    description: '根据模型参数量、量化精度（FP16/INT8/INT4）、上下文长度与批大小精算所需显存',
    descriptionEn: 'Calculate GPU VRAM requirements for Large Language Models based on parameters, quantization, context length, and batch size',
    icon: 'Cpu',
    color: '#06B6D4',
    href: '/tools/ai/gpu-calculator',
    status: 'active',
    toolType: 'calculator',
    privacyMode: 'local',
    tier: 'S',
    isPremium: false,
    seoTitle: '大模型显存计算器 · LLM GPU显存需求与量化估算 - BitNook',
    seoTitleEn: 'LLM GPU VRAM Calculator - Model Parameters & Quantization - BitNook',
    seoDescription: '精算 7B、13B、70B 等开源大模型在 FP16、BF16、INT8、INT4 量化下的模型权重、KV Cache 显存占用与显卡选型建议。',
    seoDescriptionEn: 'Estimate GPU VRAM needed to run or fine-tune open-weight LLMs with different quantization and context sizes.',
    keywords: ['大模型显存计算器', 'LLM显存估算', 'GPU显存需求', '模型量化显存', '显卡配置评估'],
    keywordsEn: ['llm vram calculator', 'gpu memory calculator', 'model quantization vram', 'huggingface model vram'],
    relatedTools: ['unit', 'radix', 'password'],
    updatedAt: '2026-03-25',
  },
]

// ==================== Helper Functions ====================

export function getAllTools(): ToolRegistryItem[] {
  return TOOLS
}

export function getActiveTools(): ToolRegistryItem[] {
  return TOOLS.filter(t => t.status === 'active')
}

export function getToolBySlug(slug: string): ToolRegistryItem | undefined {
  return TOOLS.find(t => t.slug === slug)
}

export function getToolsByCategory(category: CategorySlug): ToolRegistryItem[] {
  return TOOLS.filter(t => t.category === category && t.status === 'active')
}

export function getFeaturedTools(): ToolRegistryItem[] {
  const featuredSlugs = ['mortgage', 'salary', 'bmi', 'timestamp', 'qrcode', 'password', 'unit', 'hash']
  return featuredSlugs
    .map(slug => getToolBySlug(slug))
    .filter((t): t is ToolRegistryItem => Boolean(t))
}

export function getRelatedTools(tool: ToolRegistryItem): ToolRegistryItem[] {
  return tool.relatedTools
    .map(slug => getToolBySlug(slug))
    .filter((t): t is ToolRegistryItem => Boolean(t))
}

export function getToolsByTier(tier: ToolTier): ToolRegistryItem[] {
  return TOOLS.filter(t => t.tier === tier && t.status === 'active')
}

export function getSTierTools(): ToolRegistryItem[] {
  return getToolsByTier('S')
}
